# all services in "app" stack are monitored
rancher-alarms:
  image: ndelitski/rancher-alarms
  environment:
    ALARM_SLACK_WEBHOOK_URL: https://hooks.slack.com/services/...
    ALARM_FILTER: app/*
  labels:
      io.rancher.container.create_agent: true
      io.rancher.container.agent.role: environment
